//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RH_Server_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RH_Server_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RH_Server.Properties.RH_Server_Resources", typeof(RH_Server_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH_Server IP: {0}.
        /// </summary>
        internal static string Message_RH_Server_IP {
            get {
                return ResourceManager.GetString("Message_RH_Server_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH_Server initializing.
        /// </summary>
        internal static string RH_Server_initializing {
            get {
                return ResourceManager.GetString("RH_Server_initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH_Server READY! Now listening..
        /// </summary>
        internal static string RH_Server_READY {
            get {
                return ResourceManager.GetString("RH_Server_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Client accepted.
        /// </summary>
        internal static string RH_Server_TCP_Client_accepted {
            get {
                return ResourceManager.GetString("RH_Server_TCP_Client_accepted", resourceCulture);
            }
        }
    }
}
