//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mallaca.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mallaca.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _23tia5_centificate {
            get {
                object obj = ResourceManager.GetObject("_23tia5_centificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with IP-address: {0} has been disconnected.
        /// </summary>
        public static string ClientHandler_Client_Disconnected {
            get {
                return ResourceManager.GetString("ClientHandler_Client_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleLoginPacket:.
        /// </summary>
        public static string ClientHandler_Debug_HandleLoginPacket {
            get {
                return ResourceManager.GetString("ClientHandler_Debug_HandleLoginPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got JSON that does not define a command..
        /// </summary>
        public static string ClientHandler_Got_JSON_that_does_not_define_a_command {
            get {
                return ResourceManager.GetString("ClientHandler_Got_JSON_that_does_not_define_a_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-implemented data type: .
        /// </summary>
        public static string ClientHandler_HandlePullPacket_Non_implemented_data_type {
            get {
                return ResourceManager.GetString("ClientHandler_HandlePullPacket_Non_implemented_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved: 
        /// {0}.
        /// </summary>
        public static string ClientHandler_HandlePushPacked_Recieved {
            get {
                return ResourceManager.GetString("ClientHandler_HandlePushPacked_Recieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authtoken found in packet..
        /// </summary>
        public static string ClientHandler_No_authtoken_found {
            get {
                return ResourceManager.GetString("ClientHandler_No_authtoken_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got a packet with an invalid authentication token..
        /// </summary>
        public static string ClientHandler_Recieved_Packet_Invalid_AuthToken {
            get {
                return ResourceManager.GetString("ClientHandler_Recieved_Packet_Invalid_AuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending SyntaxError-packet to {0}.
        /// </summary>
        public static string ClientHandler_Sending_SyntaxError_packet_to {
            get {
                return ResourceManager.GetString("ClientHandler_Sending_SyntaxError_packet_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown packet.
        /// </summary>
        public static string ClientHandler_Unknown_packet {
            get {
                return ResourceManager.GetString("ClientHandler_Unknown_packet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] invalid_certificate {
            get {
                object obj = ResourceManager.GetObject("invalid_certificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
